### ISSUE TITLE
Missing offset

### ISSUE THREAD

**Issue by masa-raritan** [Legrandgroup/libezsp#28]
On this line the offset for the string length is missing.
https://github.com/Legrandgroup/libezsp/blob/689053e414a26f38e8ef513bdd927fa1ce2aa1ee/example/mainEzspTest.cpp#L267

It has to be:
`usedBytes = 6 + strLength;`

**Comment by lionelains** [comment]
Well spotted. I will fix this as soon after PR #27 is merged.

**Comment by lionelains** [comment]
Fixed in branch release: https://github.com/Legrandgroup/libezsp/commit/0ab2ea8162ff16a9826062215e537879be6061b0
