### ISSUE TITLE
Support new Raritan toolchain with c++17

### ISSUE THREAD

**Issue by masa-raritan** [Legrandgroup/libezsp#64]
The Raritan toolchain for release 3.7 will have an minimum of c++17 and the project will not compile anymore.

Changing
https://github.com/Legrandgroup/libezsp/blob/b6dded37fc136fcd5c8220c2a302d1c2ec6fae74/CMakeLists.txt#L10
to
`set(CMAKE_CXX_STANDARD 17) `
will work.

**Comment by lionelains** [comment]
I would rather leave the current requirement of C+11 for this to compile on all platforms, and patch to include the requirement of c++17 just in the Raritan build.
What is your opinion?

**Comment by masa-raritan** [comment]
Sure, this is another way to solve this. Is the current Raritan branch up to date with the release branch? 
FYI: On Fedora C++17 is supported, in Ubuntu 18.04 LTS we need a additional package (gcc-8). Ubuntu 20.04 LTS should support this out of the box.

**Comment by lionelains** [comment]
Hi @masa-raritan, the raritan branch in this github repo was deleted. I think you should now point to the [release](https://github.com/Legrandgroup/libezsp/tree/release) branch.

**Comment by lionelains** [comment]
Current code left as is to allow compilation on toolchains that do not support C+17, because this lib's requirement is C++11 as a minimum.
